apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - network-policy.yml
  - resource-quota.yml
  - limit-range.yml
  - homer/deployment.yml
  - homer/service.yml
  - homer/ingress.yml
  - it-tools/deployment.yml
  - it-tools/service.yml
  - it-tools/ingress.yml

labels:
  - pairs:
      managed-by: kustomize